# Reads user-supplied raw PCM sound-effect files (SI_SOUND_DIR/*.pcm -
# 16-bit signed little-endian mono @ SOUND_SAMPLE_RATE_HZ, see
# sounds/space_invaders/README.md) and writes a generated C source (SI_SOUND_OUT) embedding
# each as a byte array, plus a sound_table[] lookup indexed by sound_id_t
# (src/audio/sound_data.h). Invoked via add_custom_command in CMakeLists.txt
# - not meant to be included directly.
#
# The real Space Invaders cabinet's sound effects came from discrete analog
# circuitry, not a sample ROM - there's nothing to "dump" the way the video
# ROM can be. Each of these files is therefore user-supplied (your own
# recording, or converted from a legally-obtained sample pack) rather than
# vendored. Any missing file gets a 0-length placeholder instead of failing
# the build, so the rest of the project still compiles - space_invaders_plugin.c's
# voice_advance() silently no-ops playback for a 0-length sound (see sound_data.h).

# Search locations for sound samples:
# 1. SI_SOUND_DIR (e.g. roms/space_invaders/)
# 2. roms/space_invaders/samples/
# 3. sounds/space_invaders/
if(NOT EXISTS "${SI_SOUND_DIR}/shot.pcm")
    if(EXISTS "${SI_SOUND_DIR}/samples/shot.pcm")
        set(SI_SOUND_DIR "${SI_SOUND_DIR}/samples")
    else()
        get_filename_component(REPO_ROOT "${SI_SOUND_DIR}/../.." ABSOLUTE)
        if(EXISTS "${REPO_ROOT}/sounds/space_invaders/shot.pcm")
            set(SI_SOUND_DIR "${REPO_ROOT}/sounds/space_invaders")
        elseif(EXISTS "${REPO_ROOT}/roms/space_invaders/shot.pcm")
            set(SI_SOUND_DIR "${REPO_ROOT}/roms/space_invaders")
        endif()
    endif()
endif()

set(SI_SOUND_NAMES
        ufo
        shot
        player_die
        invader_die
        extra_life
        fleet1
        fleet2
        fleet3
        fleet4
        ufo_hit
)

set(SI_SOUND_ARRAYS "")
set(SI_SOUND_TABLE_ENTRIES "")
set(SI_SOUND_MISSING FALSE)

foreach(name ${SI_SOUND_NAMES})
    set(pcmfile "${SI_SOUND_DIR}/${name}.pcm")
    string(TOUPPER "${name}" name_upper)

    if(EXISTS "${pcmfile}")
        file(READ "${pcmfile}" filehex HEX)
        string(LENGTH "${filehex}" filehex_len)
        math(EXPR byte_len "${filehex_len} / 2")
        math(EXPR remainder "${byte_len} % 2")
        if(NOT remainder EQUAL 0)
            message(WARNING "generate_space_invaders_sounds.cmake: ${pcmfile} has an odd byte count (${byte_len}) - not a whole number of 16-bit samples. The last odd byte is dropped.")
        endif()
        math(EXPR frame_count "${byte_len} / 2")
        string(REGEX REPLACE "(..)" "0x\\1," c_array "${filehex}")
        string(APPEND SI_SOUND_ARRAYS "static const uint8_t sound_${name}_bytes[] __in_flash(\"sound_data\") __attribute__((aligned(2))) = { ${c_array} };\n")
        string(APPEND SI_SOUND_TABLE_ENTRIES "    [SOUND_${name_upper}] = { (const int16_t *)sound_${name}_bytes, ${frame_count} },\n")
    else()
        message(WARNING "generate_space_invaders_sounds.cmake: missing sound file ${pcmfile} (see sounds/space_invaders/README.md) - this effect will be silent until supplied.")
        string(APPEND SI_SOUND_ARRAYS "static const uint8_t sound_${name}_bytes[1] __in_flash(\"sound_data\") __attribute__((aligned(2))) = { 0 };\n")
        string(APPEND SI_SOUND_TABLE_ENTRIES "    [SOUND_${name_upper}] = { (const int16_t *)sound_${name}_bytes, 0 },\n")
        set(SI_SOUND_MISSING TRUE)
    endif()
endforeach()

if(SI_SOUND_MISSING)
    set(SI_SOUND_COMMENT "// WARNING: one or more sound files were missing at build time - those\n// effects are silent (0-length) placeholders. See sounds/space_invaders/README.md.")
else()
    set(SI_SOUND_COMMENT "// All sound effects supplied from sounds/space_invaders/ at build time.")
endif()

file(WRITE "${SI_SOUND_OUT}" "// Auto-generated by cmake/generate_sounds.cmake at build time - do not edit.
// Sound-effect PCM data, supplied locally by the user in sounds/ - not
// vendored in this repository, see sounds/README.md.
${SI_SOUND_COMMENT}
#include <stdint.h>
#include \"pico.h\"
#include \"sound_data.h\"

${SI_SOUND_ARRAYS}
const sound_sample_t sound_table[SOUND_COUNT] = {
${SI_SOUND_TABLE_ENTRIES}};
")
