# Reads Pac-Man arcade ROM and PROM files from PACMAN_ROM_DIR and writes
# a generated C source (PACMAN_ROM_OUT) defining:
# - pacman_rom[16384] (16KB Z80 program code)
# - pacman_tile_rom[4096] (4KB 8x8 character tiles)
# - pacman_sprite_rom[4096] (4KB 16x16 sprite tiles)
# - pacman_palette_prom[32] (32 bytes RGB palette)
# - pacman_color_prom[256] (256 bytes color lookup table)
# - pacman_sound_prom[256] (256 bytes 8x32 sound wavetable)

function(read_rom_or_placeholder file_path expected_len default_fill out_hex out_missing)
    if(EXISTS "${file_path}")
        file(READ "${file_path}" hex_data HEX)
        string(LENGTH "${hex_data}" hex_len)
        math(EXPR byte_len "${hex_len} / 2")
        if(NOT byte_len EQUAL expected_len)
            message(WARNING "generate_pacman_rom.cmake: ${file_path} is ${byte_len} bytes (expected ${expected_len}).")
        endif()
        set(${out_hex} "${hex_data}" PARENT_SCOPE)
        set(${out_missing} FALSE PARENT_SCOPE)
    else()
        message(STATUS "generate_pacman_rom.cmake: missing ${file_path} - substituting placeholder.")
        string(REPEAT "${default_fill}" ${expected_len} filler)
        set(${out_hex} "${filler}" PARENT_SCOPE)
        set(${out_missing} TRUE PARENT_SCOPE)
    endif()
endfunction()

# 1. Program ROMs (4x 4KB = 16384 bytes)
set(PROG_FILES
    "${PACMAN_ROM_DIR}/pacman.6e"
    "${PACMAN_ROM_DIR}/pacman.6f"
    "${PACMAN_ROM_DIR}/pacman.6h"
    "${PACMAN_ROM_DIR}/pacman.6j"
)

set(PACMAN_PROG_HEX "")
set(PACMAN_MISSING FALSE)

foreach(rf ${PROG_FILES})
    read_rom_or_placeholder("${rf}" 4096 "00" hex_chunk missing_flag)
    string(APPEND PACMAN_PROG_HEX "${hex_chunk}")
    if(missing_flag)
        set(PACMAN_MISSING TRUE)
    endif()
endforeach()

# 2. Graphics ROMs (2x 4KB = 8192 bytes)
read_rom_or_placeholder("${PACMAN_ROM_DIR}/pacman.5e" 4096 "00" PACMAN_5E_HEX m5e)
read_rom_or_placeholder("${PACMAN_ROM_DIR}/pacman.5f" 4096 "00" PACMAN_5F_HEX m5f)

# 3. PROMs (32B palette, 256B color, 256B sound)
read_rom_or_placeholder("${PACMAN_ROM_DIR}/82s123.7f" 32 "00" PACMAN_PAL_HEX mpal)
read_rom_or_placeholder("${PACMAN_ROM_DIR}/82s126.4a" 256 "00" PACMAN_COL_HEX mcol)
read_rom_or_placeholder("${PACMAN_ROM_DIR}/82s126.1m" 256 "00" PACMAN_SND_HEX msnd)

string(REGEX REPLACE "(..)" "0x\\1," PACMAN_PROG_C "${PACMAN_PROG_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," PACMAN_5E_C "${PACMAN_5E_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," PACMAN_5F_C "${PACMAN_5F_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," PACMAN_PAL_C "${PACMAN_PAL_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," PACMAN_COL_C "${PACMAN_COL_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," PACMAN_SND_C "${PACMAN_SND_HEX}")

file(WRITE "${PACMAN_ROM_OUT}" "// Auto-generated by cmake/generate_pacman_rom.cmake at build time - do not edit.
#include <stdint.h>
#include <stddef.h>

const uint8_t pacman_rom[16384] = { ${PACMAN_PROG_C} };
const size_t pacman_rom_size = 16384;

const uint8_t pacman_tile_rom[4096] = { ${PACMAN_5E_C} };
const size_t pacman_tile_rom_size = 4096;

const uint8_t pacman_sprite_rom[4096] = { ${PACMAN_5F_C} };
const size_t pacman_sprite_rom_size = 4096;

const uint8_t pacman_palette_prom[32] = { ${PACMAN_PAL_C} };
const size_t pacman_palette_prom_size = 32;

const uint8_t pacman_color_prom[256] = { ${PACMAN_COL_C} };
const size_t pacman_color_prom_size = 256;

const uint8_t pacman_sound_prom[256] = { ${PACMAN_SND_C} };
const size_t pacman_sound_prom_size = 256;
")
